### PR TITLE
Feature/biogears addon

### PR DESCRIPTION
**Pull request by StevenAWhite**
Very initial work to upgrade the Biogears Physiology driver executable.  I wanted to get this visible the current push mostly focuses on making sure it will work from a Biogears install based on core instead of the old engine repo.

### CODE REVIEW

**Comment by StevenAWhite** [comment]
Should be on top of develop now.  Or maybe not looking over the conflict list.   I see what I did one second

**Comment by StevenAWhite** [comment]
Ok, this should be good for first round review.  I forgot over the week that the branches were not named symmetricly between the two repos.

**Comment by draum** [comment]
@StevenAWhite Sorry for the delay in reviewing this - the BG build incorporation works properly, but something in the sqlite finding changes breaks linking of sqlite3 in modules that require it.  I can't merge the PR in until I resolve that problem.

**Comment by StevenAWhite** [comment]
That's cool can you send me the output.

**Pull request merged**
